#!/usr/bin/env zsh

# [[ TMUX PLUGIN MANAGER ]]
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# [[ OH MY ZSH ]]
# sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

DOTFILES=$HOME/.dotfiles
if [[ -z $STOW_FOLDERS ]]; then
	STOW_FOLDERS="bin,personal,nvim,tmux,zsh"
fi

# [[ BREW ]
command -v brew >/dev/null 2>&1 || { echo >&2 "Installing Homebrew"; \
git clone https://github.com/Homebrew/brew homebrew ; }
eval "$(homebrew/bin/brew shellenv)"
brew update --force --quiet
chmod -R go-w "$(brew --prefix)/share/zsh"
brew_install() {
    echo "\nInstalling $1"
    if brew list $1 &>/dev/null; then
        echo "${1} is already installed"
    else
        brew install $1 && echo "$1 is installed"
    fi
}
brew_install "stow"

# [[ STOW ]]
pushd $DOTFILES
git clone https://github.com/Santiago-Silvera/nvim ~/.dotfiles/nvim/.config/nvim
rm ~/.zprofile
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
	# echo "stow $folder"
	stow -D $folder
	stow -v $folder
done
popd
tmux
tmux source ~/.tmux.conf
