#!/usr/bin/env zsh

# [[ TMUX PLUGIN MANAGER ]]
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# [[ OH MY ZSH ]]
# sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

DOTFILES=$HOME/.dotfiles
if [[ -z $STOW_FOLDERS ]]; then
	STOW_FOLDERS="bin,personal,nvim,tmux,zsh"
fi

# [[ BREW ]
command -v brew >/dev/null 2>&1 || { echo >&2 "Installing Homebrew"; \
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" ;}
(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/elizabethflores/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"
brew_install() {
    echo "\nInstalling $1"
    if brew list $1 &>/dev/null; then
        echo "${1} is already installed"
    else
        brew install $1 && echo "$1 is installed"
    fi
}
brew_install "stow"
brew_install "nvim"
brew_install "tmux"

# [[ STOW ]]
pushd $DOTFILES
rm ~/.zprofile
git clone https://github.com/Santiago-Silvera/nvim ~/.dotfiles/nvim/.config/nvim
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
	stow -D $folder
	stow -v $folder
done
popd
source ~/.zshrc
source ~/.zprofile
tmux
tmux source ~/.tmux.conf
